### ISSUE TITLE
Error in load_float_data (line 163)

### ISSUE THREAD

**Issue by rampatels** [NOAA-PMEL/OneArgo-Mat#4]
% The error occurs at 7900180 and 181 as well. 
% I checked 7900180_prof.nc, it has data all dimension looks consistent with the file as well. 

% code
data = load_float_data(7900180);
% outputs in the command window
Attempting download of https://data-argo.ifremer.fr/dac/kordi/7900180/7900180_prof.nc
to ./Profiles/7900180_prof.nc ... success!
Error using reshape
Number of elements must not change. Use [] as one of the size inputs to automatically calculate the appropriate size for
that dimension.

Error in load_float_data (line 163)
            tmp = reshape(tmp, n_levels, n_prof);%, n_prof

Any help would be appreciated.

**Comment by hfrenzel-noaa** [comment]
I cannot reproduce this error. Do you have the latest version of the code?
Please also check if the files were downloaded correctly. shasum values should be:
f1e507cb54c8e6532736ecfab6c6b724391ce7bc  7900180_prof.nc
3faaebee367807a529bba11751df7b9c47e92848  7900181_prof.nc
